name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install build client
        run: |
          cd client
          npm install
          npm run build

      - name: Remove client folder
        run: rm -rf client

      - name: Push to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku git:remote -a skribbl-ai
          git push heroku main
