name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install build client
        run: |
          cd client
          npm install
          npm run build

      - name: Remove client folder
        run: rm -rf client

      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: william2010.gao@gmail.com
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
      - name: Add Heroku remote
        run: heroku git:remote --app skribbl-ai
      - name: Push to Heroku
        run: git push heroku main
